FROM python:3.7-slim

WORKDIR /app

COPY ./api_yamdb/requirements.txt ./

RUN pip3 install -r requirements.txt --no-cache-dir

COPY ./ ./

CMD ["gunicorn", "api_yamdb.wsgi:application", "--bind", "158.160.49.4:8000" ]
